version: '3.8'

services:
  postgresql:
    image: 'postgres:14.4-alpine'
    healthcheck:
      interval: 10s
      retries: 10
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${POSTGRES_USER}',
          '-P',
          '${POSTGRES_PASSWORD}'
        ]
      timeout: 45s
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - './data/postgresql:/var/lib/postgresql/data/'
    env_file:
      - '.env'
    environment:
      POSTGRES_DB: '${DATABASE_NAME:-development}'
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'